ticket/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('tasks/', views.task_list, name='task-list'),
    path('tasks/<int:task_id>/', views.task_detail, name='task-detail'),
    ]

ticket_system/ticket/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from ticket_system.ticket import views

urlpatterns = [
    path('tasks/', views.task_list, name='task-list'),
    path('tasks/<int:task_id>/', views.task_detail, name='task-detail'),
    path('tasks/<int:task_id>/edit/', views.task_edit, name='task-edit'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    ]

ticket_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tickets/', include('ticket_system.ticket.urls')),
 ]

ticket/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Client(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_executor = models.BooleanField()
    department = models.ForeignKey('Department', on_delete=models.CASCADE, null=True, blank=True)
    is_manager = models.BooleanField()

    @property
    def full_name(self):
        return f'{self.user.first_name} {self.user.last_name}'

    def __str__(self):
        return f'{self.pk}: {self.full_name}'

class Department(models.Model):
    name = models.TextField()
    description = models.TextField()

    def __str__(self):
        return f'{self.pk}: {self.name}'


class Tag(models.Model):
    text = models.CharField(max_length=20)

    def __str__(self):
        return self.text

class Task(models.Model):
    PRIORITY_CHOICES = [
        ('n', 'normal'),
        ('l', 'low'),
        ('h', 'high'),
    ]

    STATUS_CHOICES = [
        ('2d','todo'),
        ('iw','inwork'),
        ('rv','review'),
        ('dn','done'),
        ('pp','postponed')
    ]

    client = models.ForeignKey(Client, related_name = 'client', null = True, on_delete=models.SET_NULL)
    executor = models.ForeignKey(Client, related_name = 'executor', null = True, on_delete=models.SET_NULL)
    title = models.TextField()
    text = models.TextField()

    priority_client = models.CharField(
        choices =  PRIORITY_CHOICES,
        max_length = 1,
        default = 'n',
        help_text = 'For chosing priority your task',
    )

    priority_executor = models.CharField(
        choices =  PRIORITY_CHOICES,
        max_length = 1,
        default = 'n',
    )

    status = models.CharField(
        choices = STATUS_CHOICES,
        max_length = 10,
        default = '2d'
    )
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return f'{self.pk}: {self.title}'

ticket_system/ticket/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


# Create your models here.
class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_executor = models.BooleanField()
    department = models.ForeignKey('Department', blank=True, null=True, on_delete=models.SET_NULL)
    is_manager = models.BooleanField()

    @property
    def full_name(self):
        return f'{self.user.first_name} {self.user.last_name}'

    def __str__(self):
        return f'{self.pk}: {self.full_name}'

    def get_random(queryset):
        return queryset.order_by("?").first()

class Department(models.Model):
    name = models.TextField()
    description = models.TextField()

    def __str__(self):
        return f'{self.pk}: {self.name}'


class Task(models.Model):
    
    # class Meta:
    #     permissions = ( ("can_create_task", "User Can Create a new task"),
    #                     ("can_update_task", "User Can update a task"),
    #                     )

    PRIORITY_CHOICES = [
        ('n', 'Normal'),
        ('l', 'Low'),
        ('h', 'High'),
    ]
    PRIORITY_CHOICES_DICT = {
        x[0]: x[1] for x in PRIORITY_CHOICES
    }

    STATUS_CHOICES = [
        ('2d','To do'),
        ('iw','Inwork'),
        ('rv','Review'),
        ('dn','Done'),
        ('pp','Postponed')
    ]

    STATUS_CHOICES_DICT = {
        x[0]: x[1] for x in STATUS_CHOICES
    }
    
    client = models.ForeignKey(Client, related_name = 'client', null = True, on_delete=models.SET_NULL)
    executor = models.ForeignKey(Client, related_name = 'executor', null = True, on_delete=models.SET_NULL)
    title = models.TextField()
    text = models.TextField()

    priority = models.CharField(
        choices =  PRIORITY_CHOICES,
        max_length = 1,
        default = 'h',
        help_text = 'For chosing priority your task',
    )
        
    status = models.CharField(
        choices = STATUS_CHOICES,
        max_length = 10,
        default = '2d'
    )
    
    department = models.ForeignKey(Department, on_delete=models.CASCADE, blank=True, null=True)
    tag = TaggableManager(blank=True)

    def __str__(self):
        return f'{self.pk}: {self.title}'

    

ticket/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Tag, Department, Task


class AddTaskForm(forms.Form):
    title = forms.CharField(max_length=150, widget=forms.Textarea)
    text = forms.CharField(max_length=2000, widget=forms.Textarea)
    new_tag = forms.CharField(max_length=20, widget=forms.Textarea)
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), required=False)
    department = forms.ModelMultipleChoiceField(queryset=Department.objects.all(), required=False)
    priority_client = forms.ChoiceField(choices = Task.PRIORITY_CHOICES)

ticket_system/ticket/forms.py
from django import forms
from django.contrib.auth.models import User
from ticket_system.ticket.models import *
from crispy_forms.helper import FormHelper
from django.urls import reverse
from crispy_forms.layout import Submit



class TaskEditForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['executor','department','priority','status','tag']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        if self.instance.id:
            self.helper.form_action = reverse('task-edit', args=[self.instance.id])
        else:
            self.helper.form_action = reverse('task-list')
        self.helper.add_input(Submit('submit', 'Submit'))


class TaskForm(TaskEditForm):
    class Meta:
        model = Task
        fields = ['title', 'text', 'department', 'tag']    

ticket/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import *
from .forms import AddTaskForm

# Create your views here.

def task_list(request):
    tasks = Task.objects.all()
    form = AddTaskForm()
    context = {
        'title': 'Tasks',
        'tasks': tasks,
        'form': form
    }
    if request.method == 'POST':
        form = AddTaskForm(request.POST)
        if form.is_valid():
            new_task = Task(
                user=user,
                title=form.cleaned_data.get('title'),
                text=form.cleaned_data.get('text'),

            )
            new_task.save()
            new_task.tags.set(form.cleaned_data.get('tags')),
            context['form'] = AddTaskForm()
    elif request.method == 'GET':
        #if request.user == user:
        form = AddTaskForm(),
        context['form'] = form
    return render(request, 'tickets/task_list.html', context)

def task_detail(request, task_id):
    task = Task.objects.get(pk=task_id)
    context = {
        'title': task.title,
        'task': task,
    }
    return render(request, 'tickets/task_detail.html', context)

ticket_system/ticket/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import UpdateView
from ticket_system.ticket.models import Task, Client
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import authenticate
from ticket_system.ticket.forms import TaskForm, TaskEditForm



# Create your views here.
@login_required(login_url='/admin/login')
def task_list(request):
    tasks = Task.objects.all()
    
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.executor = Client.get_random(Client.objects.filter(department=form.cleaned_data.get('department')))
            new_task.client = request.user.client
            new_task.save()
            form.save_m2m()
            return HttpResponseRedirect(request.path)

    elif request.method == 'GET':
        form = TaskForm()
    
    context = {
        'title': 'Tasks',
        'tasks': tasks,
        'form': form
    }
    return render(request, 'tickets/task_list.html', context)

@login_required(login_url='/admin/login')
def task_detail(request, task_id):
    task = Task.objects.get(pk=task_id)
    context = {
        'task': task,
        'priority': Task.PRIORITY_CHOICES_DICT[task.priority],
        'status':  Task.STATUS_CHOICES_DICT[task.status],
    }
    # import pdb; pdb.set_trace()
    return render(request, 'tickets/task_detail.html', context)
    

@login_required(login_url='/admin/login')
@permission_required("ticket.change_task")
def task_edit(request, task_id):
    task = Task.objects.get(pk=task_id)
    
    if request.method == 'GET':
        form = TaskEditForm(instance=task)

    elif request.method == 'POST':
        form = TaskEditForm(request.POST, instance=task)
        if form.is_valid():
            task = form.save(commit=False)
            form.save_m2m()
            task.save()
            return redirect('task-detail',task_id=task.id)
            
    context = {
        'task': task,
        'form': form
    }
    
    return render(request, 'tickets/task_detail_edit.html', context)
    

ticket_system/templates/tickets/base.html
{% extends 'tickets/bootstrap.html' %}

{% load bootstrap4 %}

{% block bootstrap4_title %}
  
{% endblock %}


        {% block bootstrap4_content %}
        <div class="container">
            {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

            {% block content %}(no content){% endblock %}
        </div>

        {% endblock %}

      

{% block bootstrap4_form %}
{% endblock %}

{% block bootstrap4_after_content %}
  <div id="footer" align="center">
    {% block footer %}
    &copy; Copyright 2020 by <a href="http://mydomain.tld">anybody</a>.
    {% endblock %}
  </div>
{% endblock %}

ticket_system/templates/tickets/bootstrap.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% block bootstrap4_title %}{% endblock %}

ticket_system/templates/tickets/task_detail.html
{% extends "tickets/base.html" %}

<div class="container-fluid">
{% block bootstrap4_title %}
{{ task.title }}
{% endblock %}

{% block bootstrap4_content %}
<div>
    <div class="d-block p-2 bg-primary text-white text-right" >
        <div class="clearfix">
            <a type="button" class="btn btn-secondary float-left" href="{% url 'task-list' %}">Task list</a>
            {% if perms.ticket.change_task %}
                <a type="button" class="btn btn-secondary float-left" href="{% url 'task-edit' task.id %}">Edit</a>
            {% endif %}
            <h4> Hello, {{ user.client.full_name }}</h4> 
        </div>
    </div>
    
<div class="row">

    <div class="col-sm-1"></div>

    <div class="col-sm">
        
        <h1 class="text-center">{{ task.title }} </h1>
        
        <dl class="row">
            <dt class="col-sm-3">Task text:</dt>
            <dd class="col-sm-9">{{ task.text }}</dd>
        </dl>

        <dl class="row">
            <dt class="col-sm-3">Created by:</dt>
            <dd class="col-sm-9">{{ task.client.full_name }}</dd>
        </dl>

        <dl class="row">
            <dt class="col-sm-3">Executor:</dt>
            <dd class="col-sm-9">{{ task.executor.full_name }} from {{ task.department.name }} department</dd>
        </dl>

        <dl class="row">
            <dt class="col-sm-3">Priority:</dt>
            <dd class="col-sm-9">{{ priority }}</dd>
        </dl>
        
        <dl class="row">
            <dt class="col-sm-3">Status:</dt>
            <dd class="col-sm-9">{{ status }}</dd>
        </dl>
        
        <dl class="row">
            <dt class="col-sm-3">Tags:</dt>
            <dd class="col-sm-9">
                {% for tag in task.tag.all %}
                    <a>{{ tag.name }}</a>
                {% endfor %}
            </dd>
        </dl>

    </div>

</div>

</div>
  {% endblock %}
</div>

ticket_system/templates/tickets/task_detail_edit.html
{% extends "tickets/base.html" %}

{% load crispy_forms_tags %}

<div class="container-fluid">
{% block bootstrap4_title %}
{{ task.title }}
{% endblock %}

{% block bootstrap4_content %}
<div>
    <div class="d-block p-2 bg-primary text-white text-right" >
        <div class="clearfix">
            <a type="button" class="btn btn-secondary float-left" href="{% url 'task-list' %}">Task list</a>
            <a type="button" class="btn btn-secondary float-left" href="{% url 'task-detail' task.id %}">Back</a>
            <h4> Hello, {{ user.client.full_name }}</h4> 
        </div>
    </div>
    
<div class="row">

    <div class="col-sm-1"></div>

    <div class="col-sm" >

        <h1 class="text-center">{{ task.title }} </h1>
        
        <dl class="row">
            <dt class="col-sm-3">Task text:</dt>
            <dd class="col-sm-9">{{ task.text }}</dd>
        </dl>

        <dl class="row">
            <dt class="col-sm-3">Created by:</dt>
            <dd class="col-sm-9">{{ task.client.full_name }}</dd>
        </dl>

        {% crispy form form.helper %}
        
      
    </div>
    
</div>

</div>
  {% endblock %}
</div>

ticket_system/templates/tickets/task_list.html
{% extends "tickets/base.html" %}

{% block bootstrap4_title %}
{{ title }}
{% endblock %}


{% block bootstrap4_content %}

<h4 class="d-block p-2 bg-primary text-white text-right" >Hello, {{ user.client.full_name }}</h4>

<div class="row">
  
  <div class="col-sm">
    <h1 align="center" >{{ title }}</h1>
        
    <table class="table">
      <thead>
        <tr>
          
          <th scope="col">Title</th>
          <th scope="col">Text problem</th>
          
          {% if perms.ticket.change_task or perms.ticket.add_task%}
            <th scope="col">Department</th>
            <th scope="col">Tags</th>
          {% endif %}

          {% if perms.ticket.change_task or perms.ticket.view_task %}
            <th scope="col">Priority</th>
            <th scope="col">Status</th>
          {% endif %}
          
          {% if perms.ticket.change_task %}
            <th scope="col">Client</th>
            <th scope="col">Executor</th>
          {% endif %}

        </tr>
      </thead>
      {% for task in tasks %}
      <tbody>
        <tr href="{% url 'task-detail' task.id %}" >
          
          <td><a href="{% url 'task-detail' task.id %}">{{ task.title }}</a></td>
          <td><a href="{% url 'task-detail' task.id %}">{{ task.text }}</a></td>
          
          {% if perms.ticket.change_task or perms.ticket.add_task%}
            <td><a href="{% url 'task-detail' task.id %}">{{ task.department.name }}</a></td>
            <td><a href="{% url 'task-detail' task.id %}">
              {% for tag in task.tag.all %}
                <a>{{ tag.name }}</a>
              {% endfor %}</a>
            </td>
          {% endif %}
          
          {% if perms.ticket.change_task or perms.ticket.view_task %}
            <td><a href="{% url 'task-detail' task.id %}">{{ task.priority }}</a></td>
            <td><a href="{% url 'task-detail' task.id %}">{{ task.status }}</a></td>
          {% endif %}
          
          {% if perms.ticket.change_task %}
            <td><a href="{% url 'task-detail' task.id %}">{{ task.client.full_name }}</a></td>
            <td><a href="{% url 'task-detail' task.id %}">{{ task.executor.full_name }}</a></td>
          {% endif %}

        </tr>
      </tbody>
      {% endfor %}
    </table>


    
    
  </div>
  
  {% if perms.ticket.add_task %}

  <div class="col-sm-4">

    

      {% block bootstrap4_form %}
      
      <h2>Add new Task</h2>
      <form action="{% url 'task-list' %}" method="POST">
      {% csrf_token %}

      {{ form.as_p }}
    
      <input type="submit" value="Add Task">
      </form>
      {% endblock %}


  </div>

  {% endif %}
  
</div>
{% endblock %}

        


     